### PR TITLE
modified css

### PR DESCRIPTION
**Pull request by JerJohn15**
- added login box
- centered paragraphs so that 'create quiz' link is centered on 'adminOption'
- changed bk color for reg box div

### CODE REVIEW

**Comment by msabbota** [comment]
Jeremiah,
     Look at your diffs, I think there is something wrong with what you're trying to check in. I'm not sure how you pushed these back into your branch as I'm not seeing differences between files, just full replace.

**Comment by JerJohn15** [comment]
@msabbota 

No, I'm using Eclipse. I tested all of my changes on fiddle first and then I modified them on Eclipse. Most of it was just copying and pasting over my original code (i.e. the 'register_box'), the rest were just deletions (i.e. removing "//include 'quiz.html';" from the bottom of 'index.php'). 
.

**Comment by msabbota** [comment]
Jeremiah,
   Please see attached.  However you’re cutting and pasting is adding invisible control characters to the code that are not UNIX/Linux compatible.  This will break PHP parsing as well.  You need to make sure eclipse is set remove these or you’ll need to run the files through a dos2unix converter.

Let me know if you’re not sure how to clean up and i’ll help you correct.

Cheers,
—Mike





On March 26, 2015 at 11:41:25 AM, JerJohn15 (notifications@github.com) wrote:

@msabbota

No, I'm using Eclipse. I tested all of my changes on fiddle first and then I modified them on Eclipse. Most of it was just copying and pasting over my original code (i.e. the 'register_box'), the rest were just deletions (i.e. removing "//include 'quiz.html';" from the bottom of 'index.php').
.

**Comment by JerJohn15** [comment]
@msabbota 

Mike, 

I'm not sure on how to clean this up in eclipse. If we have time during/before class this evening we can fix it then.

**Comment by msabbota** [comment]
Can't auto-merge due to being too many revisions behind master and conflicts caused by invisible control characters.  Rejecting merge request.

**Pull request closed without merging**
