### PR TITLE
Please review current branch

### PR DESCRIPTION
**Pull request by msabbota**
- Integrated and simiplified loging, CSS and javascript includes
   - Still need to skin and add grading
   - Added images for account creation
   - Can be reviewed at http://cs473.sabbota.com:8182/index.php before pushing to master

See current changes, need to clean up some of the skins.  Want someone else to review and commit to master.

### CODE REVIEW

**Comment by JerJohn15** [comment]
Mike,

I'm in the process of reviewing the changes you've made. I have an unrelated question though:

When I make 'commits' to the 'master branch', which site do the changes go into effect in http://cs473.sabbota.com:8182/index.php  or  http://cs473.sabbota.com?

I've made changes to the bk color but it only shows up on the second link and not the first. Do you have to accept the changes before they go into effect?

**Comment by msabbota** [comment]
Git is joined to the server.  Checking into git does automatically
publish.  I just update it by pulling from master.

**Comment by msabbota** [comment]
Ugh, git DOESN'T automatically publish.   I just pull from master on the
server.

**Comment by JerJohn15** [comment]
Ok, so which link is the one that we should be checking our changes on and will be using for our presentation, the first one or the second one that I posted?

**Comment by msabbota** [comment]
You should check into a branch and another of us will merge into to master
and review.  We'll pull from master to the site before our presentation,
after we've run our test plan against it).

**Comment by JerJohn15** [comment]
Okay. 

I can't test the images you've implemented, as the 'create account' hyperlink is not showing up on the link you've provided. 

Also, add these lines of code to 'usersOption.php'

  
        
        
          <p><a href="take_quiz.html">Take Exam</a></p>
        <br>
        <br>
        <br>
        <p><a href="logout.php">Logout</a></p>

**Comment by msabbota** [comment]
Okay.

I can't test the images you've implemented, as the 'create account'
hyperlink is not showing up on the link you've provided.

*Are you sure? I've tested on three different browsers and it's visible for
me.  Little sloppy as it's unskinned, but the link is there.*


Also, add these lines of code to 'usersOption.php'

*What is your justification for having logout there and not where I placed
it in index?  It should exist with the 'login/role display in index.php.
This way formatting for the user information is the same across admin and
user roles.  In addition, no changes need to be made or concerned with if
future roles/requirements are ever developed.*



      <p><a href="take_quiz.html">Take Exam</a></p>
    <br>
    <br>
    <br>
    <p><a href="logout.php">Logout</a></p>

Have dinner at 8, will be back online after.

**Comment by JerJohn15** [comment]
Sorry, I meant to remove that line from the code (the logout). 

In regards to the 'create account', I'm able to see it now, as well as the bk color changes I had made earlier. (There seems to be a delay in seeing the updates on that link)

**Comment by msabbota** [comment]
Weird, I haven’t pushed any changes in a bit (hour or two).  You may want to check your browser cache.  It’s possible that it is caching things longer than expected.

—Mike

On March 25, 2015 at 7:41:31 PM, JerJohn15 (notifications@github.com) wrote:

Sorry, I meant to remove that line from the code (the logout).

In regards to the 'create account', I'm able to see it now, as well as the bk color changes I had made earlier. (There seems to be a delay in seeing the updates on that link)

**Comment by JerJohn15** [comment]
It seems to be doing that with both browsers I've tried (IE and Firefox). There were also sometimes where I would enter in the link and it wouldn't show the regular homepage but some other page part of the site I had been to recently. 

Other than that, the changes you've made seem good.

**Pull request merged**
