### PR TITLE
Fixed css formatting

### PR DESCRIPTION
**Pull request by JerJohn15**
-Fixed text in contents box from not being centered
-Deleted comment

### CODE REVIEW

**Comment by JerJohn15** [comment]
@msabbota 
Double check my changes in 'create_quiz'. I'm not sure if by me including 'mcontents box' in create_quiz will mess up  the css graphics/formatting that you've included in create_quiz when a regular user is logging in. 

Also, I'm not sure why the 'copyright' text on the index.php page does not default to the bottom of the page, like on the page with the login screen, when a regular user logs in. I was trying to figure out where div class="footer", (from footer.php) was in the css file but couldn't find it.

Lastly, how did you, or whoever implemented this, format the buttons to be centered on the page where the user takes the exam? I'm trying to center the buttons on http://cs473.sabbota.com:8182/create_quiz.html but so far I'm only able to center the text.

**Comment by msabbota** [comment]
Nimin, please review Jeremiahs questions for create quiz as that is your baby.

Jeremiah, it is all CSS positioning.  It's margin alignment, padding and absolute, floating or fixed positioning.

**Comment by JerJohn15** [comment]
alright, I'll keep experimenting with it.

On Fri, Mar 27, 2015 at 7:16 PM, msabbota <notifications@github.com> wrote:

> Nimin, please review Jeremiahs questions for create quiz as that is your
> baby.
>
> Jeremiah, it is all CSS positioning. It's margin alignment, padding and
> absolute, floating or fixed positioning.
>
> Sent from my iPhone
>
> > On Mar 27, 2015, at 7:12 PM, JerJohn15 <notifications@github.com> wrote:
> >
> > @msabbota
> > Double check my changes in 'create_quiz'. I'm not sure if by me
> including 'mcontents box' in create_quiz will mess up the css
> graphics/formatting that you've included in create_quiz when a regular user
> is logging in.
> >
> > Also, I'm not sure why the 'copyright' text on the index.php page does
> not default to the bottom of the page, like on the page with the login
> screen, when a regular user logs in. I was trying to figure out where div
> class="footer", (from footer.php) was in the css file but couldn't find it.
> >
> > Lastly, how did you, or whoever implemented this, format the buttons to
> be centered on the page where the user takes the exam? I'm trying to center
> the buttons on http://cs473.sabbota.com:8182/create_quiz.html but so far
> I'm only able to center the text.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CS473-Group3/Quizzer/pull/10#issuecomment-87117993>.
>



-- 
 Jeremiah Johnson
ACDP Computer Science

**Comment by JerJohn15** [comment]
Mike,

Disregard the first part of my comment I had made earlier, regarding adding the 'mcontent_box" in create_quiz.php, it won't cause any issues. I've also made some pushes in my branch as you'll see in my request. I'm not going to worry about the copyright footer not staying fixed at the bottom of the page when the user is taking the exam (it moves down once the user selects an exam).

Other than that, I think I've fixed all of the changes I had mentioned earlier.  Unless you see anything I need to fix, you can go ahead and accept.

**Comment by msabbota** [comment]
Manual conflict resolution required, unable to review and submit before sprint/end tomorrow.  Moving to backlog for next sprint.

**Pull request closed without merging**
